galaxy_info:
  role_name: hcplat_agents
  author: Hybrid Platform Team
  description: Platform agents
  company: Cisco
  license: CiscoInternal

  min_ansible_version: 2.1

  # Provide a list of supported platforms, and for each platform a list of versions.
  # If you don't wish to enumerate all versions for a particular platform, use 'all'.
  # To view available platforms and versions (or releases), visit:
  # https://galaxy.ansible.com/api/v1/platforms/
  #
  platforms:
    - name: Alpine
    - name: EL
      versions:
        - 6
        - 7
        - 8
    - name: Ubuntu
      versions:
        - xenial
        - bionic
        - focal
    - name: Debian
      versions:
        - jessie
        - stretch
        - buster
    - name: Amazon Linux
        - 2018.03
        - 2

  galaxy_tags:
    - hplat_agents
    - cloudwatch
    - linux

dependencies: []
  # List your role dependencies here, one per line. Be sure to remove the '[]' above,
  # if you add dependencies to this list.
