---

- block:
  # Download, Validate and Install cloudwatch agent rpm on CentOS & RHEL. 
  # Cloudwatch for Cloud9 Amazon linux images comes preinstalled.
  - name: Download cloudwatch-agent gpg key on RedHat
    get_url:
      url: "https://s3.amazonaws.com/amazoncloudwatch-agent/assets/amazon-cloudwatch-agent.gpg"
      dest: "/tmp/amazon-cloudwatch-agent.gpg"

  - name: Import cloudwatch-agent gpg key to rpm db
    rpm_key: 
      key: "/tmp/amazon-cloudwatch-agent.gpg"
      state: present

  - name: Download cloudwatch-agent rpm
    get_url:
      url: "https://s3.amazonaws.com/amazoncloudwatch-agent/{{ansible_distribution | lower}}/amd64/{{cloudwatch_version}}/amazon-cloudwatch-agent.rpm"
      dest: "/tmp/amazon-cloudwatch-agent.rpm"

  # Download cloudwatch agent signature
  - name: Download cloudwatch-agent signature
    get_url:
      url: "https://s3.amazonaws.com/amazoncloudwatch-agent/{{ansible_distribution | lower}}/amd64/{{cloudwatch_version}}/amazon-cloudwatch-agent.rpm.sig"
      dest: "/tmp/amazon-cloudwatch-agent.rpm.sig"

  # Validate cloudwatch agent signature
  - name: Verify cloudwatch-agent package signature
    command: "gpg --verify amazon-cloudwatch-agent.rpm.sig amazon-cloudwatch-agent.rpm"
    register: verified_sig
    failed_when: "'BAD' in verified_sig.stderr"
    changed_when: false
    args:
      chdir: "/tmp"

  # Install cloudwatch agent
  - name: Install cloudwatch-agent rpm
    yum:
      name: "/tmp/amazon-cloudwatch-agent.rpm"
      disable_gpg_check: "yes"
      state: present

  # Copy default cloudwatch agent config file      
  - name: Copy amazon-cloudwatch-agent configuration file
    copy: 
      src: files/amazon-cloudwatch-agent.json 
      dest: /opt/aws/amazon-cloudwatch-agent/etc/amazon-cloudwatch-agent.json
      owner: root
      group: root
      mode: '0644'

  # Cleanup Installation Files
  - name: Cleanup installation files on RedHat
    file:
      path: "{{ item }}"
      state: absent
    with_items:
      - "/tmp/amazon-cloudwatch-agent.rpm"
      - "/tmp/amazon-cloudwatch-agent.rpm.sig"
      - "/tmp/amazon-cloudwatch-agent.gpg"
  when:
    - ansible_facts['os_family'] == "RedHat"

- block:
  # Download, Validate and Install cloudwatch agent deb package for Ubuntu
  - name: Download cloudwatch-agent gpg key on RedHat
    get_url:
      url: "https://s3.amazonaws.com/amazoncloudwatch-agent/assets/amazon-cloudwatch-agent.gpg"
      dest: "/tmp/amazon-cloudwatch-agent.gpg"
      
  - name: Install cloudwatch-agent gpg key on Ubuntu
    apt_key:
      file: "/tmp/amazon-cloudwatch-agent.gpg"
      state: present

  - name: Download cloudwatch-agent Ubuntu package
    get_url:
      url: "https://s3.amazonaws.com/amazoncloudwatch-agent/ubuntu/amd64/{{cloudwatch_version}}/amazon-cloudwatch-agent.deb"
      dest: /tmp/amazon-cloudwatch-agent.deb

  # Download cloudwatch agent signature
  - name: Download cloudwatch-agent ubuntu signature
    get_url:
      url: "https://s3.amazonaws.com/amazoncloudwatch-agent/ubuntu/amd64/{{cloudwatch_version}}/amazon-cloudwatch-agent.deb.sig"
      dest: /tmp/amazon-cloudwatch-agent.rpm.sig

  # Validate Cloudwatch agent signature
  - name: Verify cloudwatch-agent ubuntu package signature
    command: gpg --verify amazon-cloudwatch-agent.deb.sig amazon-cloudwatch-agent.deb
    register: verified_sig
    failed_when: "'BAD' in verified_sig.stderr"
    changed_when: false
    args:
      chdir: /tmp

  # Install cloudwatch agent
  - name: Install cloudwatch-agent deb package
    apt:
      deb: "/tmp/amazon-cloudwatch-agent.deb"

  # Copy default cloudwatch agent config file      
  - name: Copy amazon-cloudwatch-agent configuration file
    copy: 
      src: files/amazon-cloudwatch-agent.json 
      dest: /opt/aws/amazon-cloudwatch-agent/etc/amazon-cloudwatch-agent.json
      owner: root
      group: root
      mode: '0644'      

  # Cleanup Installation Files
  - name: Cleanup installation files on Ubuntu
    file:
      path: "{{ item }}"
      state: absent
    with_items:
      - "/tmp/amazon-cloudwatch-agent.deb"
      - "/tmp/amazon-cloudwatch-agent.deb.sig"
      - "/tmp/amazon-cloudwatch-agent.gpg"
  when:
    - ansible_facts['distribution'] == "Ubuntu"
  # end of block - apply sudo to all tasks in file
  become: yes
  become_user: root
  become_method: sudo